env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 9
  sourceType: script
  ecmaFeatures:
    jsx: true
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
