matrix:
  include:
    - language: python
      python: 3.6
      before_script:
        - pip install pipenv
        - pipenv install --dev
      script:
        - pelican content -s pelicanconf.py

    - language: node_js
      node_js: node
      before_script:
      	- npm install grunt
        - npm install
      script:
        - grunt test
