# Don't download all repository history, that save a time:
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 1

# Trusty by default:
# https://stackoverflow.com/a/21133609/5951529
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis CI doesn't support 32-bit platforms:
# https://stackoverflow.com/a/37087813/5951529
language: python

python: 3.6

# Multiple scripts
# http://bit.ly/2ow2DvL
env:
  - GRUNT_COMMAND=build
  - GRUNT_COMMAND=publish

# Sections:
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
# https://stackoverflow.com/a/34384262/5951529

before_install:
  # Virtual environment inside project directory:
  # https://jcutrer.com/howto/dev/python/pipenv-pipfile
  # “setx PIPENV_VENV_IN_PROJECT 1” for Windows
  - export PIPENV_VENV_IN_PROJECT=1
  # Ignore already existing virtual environments:
  # https://github.com/menzenski/pipenv-travis-test/blob/develop/.travis.yml
  - export PIPENV_IGNORE_VIRTUALENVS=1
  - shopt -s globstar

install:
  # [NOTE] Parallelshell works, but no time economy, compare:
  # https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347254717
  # https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347267767
  - sudo apt-get install parallel
  # Install on Ubuntu
  - git clone https://github.com/htacg/tidy-html5.git
  - cd tidy-html5
  - cd build/cmake
  - cmake ../..
  - cmake --build . --config Release
  - sudo make install
  - cd ../../..
  - echo $PWD
  - bash ci/travis_install.sh

# Check, that virtual environment install inside project.
before_script:
  # Get current working directory:
  # https://unix.stackexchange.com/a/188191/237999
  - echo $PWD
  - pipenv --venv

script:
  - grunt $GRUNT_COMMAND
  - cd output && ../grunt/tidy.sh