# Trusty by default:
# https://stackoverflow.com/a/21133609/5951529
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
language: python

python: 3.6

# Multiple scripts
# http://bit.ly/2ow2DvL
env:
  - GRUNT_COMMAND=test
  - GRUNT_COMMAND=build

# Sections:
# https://stackoverflow.com/a/34384262/5951529
before_install:
  - pip install --upgrade pip
  - npm install --global npm

install:
  - pip install pipenv
  - pipenv install --dev
  # Grunt tasks needs grunt-cli globally:
  # https://stackoverflow.com/a/21133609/5951529
  - npm install -g grunt-cli
  - npm install

script:
  - grunt $GRUNT_COMMAND