# Don't download all repository history, that save a time:
# https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth
git:
  depth: 1

# Trusty by default:
# https://stackoverflow.com/a/21133609/5951529
# https://blog.travis-ci.com/2017-07-11-trusty-as-default-linux-is-coming
# Travis CI doesn't support 32-bit platforms:
# https://stackoverflow.com/a/37087813/5951529
language: python

python: 3.6

# Multiple scripts
# http://bit.ly/2ow2DvL
env:
  - GRUNT_COMMAND=build
  - GRUNT_COMMAND=publish

# Sections:
# https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle
# https://stackoverflow.com/a/34384262/5951529

before_install:
  # Virtual environment inside project directory:
  # https://jcutrer.com/howto/dev/python/pipenv-pipfile
  # “setx PIPENV_VENV_IN_PROJECT 1” for Windows
  - export PIPENV_VENV_IN_PROJECT=1
  # Ignore already existing virtual environments:
  # https://github.com/menzenski/pipenv-travis-test/blob/develop/.travis.yml
  - export PIPENV_IGNORE_VIRTUALENVS=1

install:
  # [NOTE] Parallelshell works, but no time economy, compare:
  # https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347254717
  # https://travis-ci.org/Kristinita/SashaPelicanTest/jobs/347267767
  - sudo apt-get install parallel
  - bash tidy/tidy-install.sh
  - bash ci/travis-install.sh

script:
  - grunt $GRUNT_COMMAND
  # Fix permission denied:
  # https://stackoverflow.com/a/46818913/5951529
  - grunt shell:tidymodify

after_success:
  - grunt shell:tidyvalidate


# Automatically deploy site to GitHub Pages:
# https://docs.travis-ci.com/user/deployment
# https://docs.travis-ci.com/user/deployment/pages/
# Changes not deploy, if pull request:
# https://docs.travis-ci.com/user/deployment#Pull-Requests
# If “script” failed, deploying doesn't run:
# else “pelican_scaffold”, deploy run, even if “script” failed, don't use “pelican_scaffold”:
# https://github.com/textbook/pelican_scaffold
deploy:
  provider: pages
  on:
    branch: SashaDevelop
    # Deploy site, only if “grunt publish”, if “grunt” — not deploy:
    # https://docs.travis-ci.com/user/deployment#Conditional-Releases-with-on%3A
    condition: $GRUNT_COMMAND = publish
  # [FIXME] Downgrade dpl for correct deploying to GitHub Pages:
  # https://github.com/travis-ci/travis-ci/issues/9312
  edge:
    branch: v1.8.47
  # Don't overwrite commit history of destination repository:
  # https://docs.travis-ci.com/user/deployment/pages/
  keep-history: true
  # Don't clean output folder:
  # ttps://docs.travis-ci.com/user/deployment/pages/
  skip-cleanup: true
  target-branch: master
  local-dir: output
  repo: Kristinita/SashaTravis.github.io
  # “GITHUB_API_KEY” and “GITHUB_EMAIL” is secure variables, that set in repository sittings:
  # https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings
  # https://docs.travis-ci.com/user/deployment/pages/#Setting-the-GitHub-token
  github-token: $GITHUB_API_KEY
  # e-mail: $GITHUB_EMAIL
  # name: Kristinita
  committer-from-gh: true
  fqdn: kristi.ru
  project-name: "Kristinita's Search"
  verbose: true