environment:

  GRUNT_COMMAND: test
  GRUNT_COMMAND: build

  matrix:

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.4"
      PYTHON_ARCH: "64"

platform: x64

install:

  # Needs, because will get messages as:
  # «flake8 is not recognized»
  # https://github.com/ogrisel/python-appveyor-demo/blob/master/appveyor.yml
  # Python 2 by default, see:
  # https://www.appveyor.com/docs/build-environment/#python
  # https://ci.appveyor.com/project/Kristinita/erichek/build/1.0.3
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  - cmd: choco install nodejs -y
  - cmd: pip install --upgrade pip
  - cmd: pip install pipenv
  - cmd: setx PIPENV_VENV_IN_PROJECT 1
  - cmd: pipenv install --dev
  - cmd: npm install -g grunt-cli
  - cmd: npm install

test_script:
  - node --version
  - npm --version

build_script:

  # Needs AppVeyor console set, see:
  # https://stackoverflow.com/a/48093971/5951529
  - cmd: set PYTHONIOENCODING=utf-8
  - cmd: grunt %GRUNT_COMMAND%
